server:
  port: 9003
spring:
  application:
    name: caidan-manager
  rabbitmq:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    caidan-user:
      path: /api-user/**
      service-id: caidan-user
    caidan-quartz:
      path: /api-quartz/**
      service-id: caidan-quartz
      
jwt:
  config:
    key: caidan
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

  
      
      
